#ifndef HttpResponseCodesDefination
#define HttpResponseCodesDefination
#define StatusCode int

/* 1XX INFORMATIONAL RESPONSE 
AN INFORMATIONAL RESPONSE INDICATES THAT THE REQUEST WAS RECEIVED AND UNDERSTOOD. IT IS ISSUED ON A PROVISIONAL BASIS WHILE REQUEST PROCESSING CONTINUES. IT ALERTS THE CLIENT TO WAIT FOR A FINAL RESPONSE.
*/
#define CONTINUE 100 
#define SWITCHING_PROTOCOLS 101
#define PROCESSING 102
#define EARLY_HINTS 103

/* 2XX SUCCESS 
THIS CLASS OF STATUS CODES INDICATES
 THE ACTION REQUESTED BY THE CLIENT WAS RECEIVED, UNDERSTOOD, AND ACCEPTED*/

#define OK 200
#define CREATED 201
#define ACCEPTED 202
#define NON_AUTHORITATIVE_INFORMATION 203
#define NO_CONTENT 204
#define RESET_CONTENT 205
#define PARTIAL_CONTENT 206
#define MULTI_STATUS 207
#define ALREADY_REPORTED 208
#define IM_USED 226

/* 3XX REDIRECTION
THIS CLASS OF STATUS CODE INDICATES THE CLIENT MUST TAKE ADDITIONAL ACTION TO COMPLETE THE REQUEST.
MANY OF THESE STATUS CODES ARE USED IN URL REDIRECTION.
*/

#define MULTIPLE_CHOICES 300
#define MOVED_PERMANENTLY 301
#define FOUND 302
#define SEE_OTHER 303
#define NOT_MODIFIED 304
#define USE_PROXY 305
#define SWITCH_PROXY 306
#define TEMPORARY_REDIRECT 307
#define PERMANENT_REDIRECT 308

/* 4XX CLIENT ERRORS
THIS CLASS OF STATUS CODE IS INTENDED 
FOR SITUATIONS IN WHICH THE ERROR SEEMS TO HAVE BEEN CAUSED BY THE CLIENT.
*/
#define BAD_REQUEST 400
#define UNAUTHORIZED 401
#define PAYMENT_REQUIRED 402
#define FORBIDDEN 403
#define NOT_FOUND 404
#define METHOD_NOT_ALLOWED 405
#define NOT_ACCEPTABLE 406
#define PROXY_AUTHENTICATION_REQUIRED 407
#define REQUEST_TIMEOUT 408
#define CONFLICT 409
#define GONE 410
#define LENGTH_REQUIRED 411
#define PRECONDITION_FAILED 412
#define PAYLOAD_TOO_LARGE 413
#define URI_TOO_LONG 414
#define UNSUPPORTED_MEDIA_TYPE 415
#define RANGE_NOT_SATISFIABLE 416
#define EXPECTATION_FAILED 417
#define I_AM_A_TEAPOT 418
#define MISDIRECTED_REQUEST 421
#define UNPROCESSABLE_ENTITY 422
#define LOCKED 423
#define FAILED_DEPENDENCY 424
#define TOO_EARLY 425
#define UPGRADE_REQUIRED 426
#define PRECONDITION_REQUIRED 428
#define TOO_MANY_REQUESTS 429
#define REQUEST_HEADER_FIELDS_TOO_LARGE 431
#define UNAVAILABLE_FOR_LEGAL_REASONS 451

/*
5XX SERVER ERRORS
THE SERVER FAILED TO FULFILL A REQUEST
*/
#define INTERNAL_SERVER_ERROR 500 
#define NOT_IMPLEMENTED 501
#define BAD_GATEWAY 502
#define SERVICE_UNAVAILABLE 503
#define GATEWAY_TIMEOUT 504
#define HTTP_VERSION_NOT_SUPPORTED 505
#define VARIANT_ALSO_NEGOTIATES 506
#define INSUFFICIENT_STORAGE 507
#define LOOP_DETECTED 508 
#define NOT_EXTENDED 510
#define NETWORK_AUTHENTICATION_REQUIRED 511


#endif

  
 

